apiVersion: v1
baseDomain: BASEDOMAIN
networking:
  networkType: OVNKubernetes
  machineCIDR: MACHINECIDR
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 24
  serviceNetwork:
    - 172.30.0.0/16
metadata:
  name: CLUSTERNAME
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    externalBridge: EXTERNAL_BRIDGE
    libvirtURI: qemu+ssh://root@HYPERVISOR/system
    provisioningNetwork: "Disabled"
    apiVIP: APIVIP
    ingressVIP: INGRESSVIP
    bootstrapOSImage: http://HELPERNODE:9000/QEMUIMAGE
    clusterOSImage: http://HELPERNODE:9000/OSTACKIMAGE
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: redfish-virtualmedia://HELPERNODE:8080/redfish/v1/Systems/master0id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:05 
        # bootMode legacy required, sushy-tools fails with UEFI: https://storyboard.openstack.org/#!/story/2008597
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: openshift-master-1
        role: master
        bmc:
          address: redfish-virtualmedia://HELPERNODE:8080/redfish/v1/Systems/master1id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:06
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: openshift-master-2
        role: master
        bmc:
          address: redfish-virtualmedia://HELPERNODE:8080/redfish/v1/Systems/master2id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:07
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
imageContentSources:
  - mirrors:
      - REGISTRYHOSTNAME:5000/ocp4
      - REGISTRYHOSTNAME:5000/ocp4/release
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
      - REGISTRYHOSTNAME:5000/ocp4
      - REGISTRYHOSTNAME:5000/ocp4/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
additionalTrustBundle: |
  REGISTRYCA
pullSecret: 'PULLSECRET'
sshKey: 'SSHPUBKEY'
