apiVersion: v1
baseDomain: BASEDOMAIN
networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 192.168.58.0/24
  - cidr: 2600:52:7:58::0/64
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 24
  - cidr: fd01::/48
    hostPrefix: 64
  serviceNetwork:
    - 172.30.0.0/16
    - fd02::/112
metadata:
  name: CLUSTERNAME
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    externalBridge: EXTERNAL_BRIDGE
    libvirtURI: qemu+ssh://root@192.168.58.1/system
    provisioningNetwork: "Disabled"
    apiVIP: 192.168.58.103
    ingressVIP: 192.168.58.102
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.58.100:8080/redfish/v1/Systems/master0id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:05 
        # bootMode legacy required, sushy-tools fails with UEFI: https://storyboard.openstack.org/#!/story/2008597
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: openshift-master-1
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.58.100:8080/redfish/v1/Systems/master1id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:06
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
      - name: openshift-master-2
        role: master
        bmc:
          address: redfish-virtualmedia://192.168.58.100:8080/redfish/v1/Systems/master2id
          username: ADMIN
          password: ADMIN
          disableCertificateVerification: True
        bootMACAddress: DE:AD:BE:FF:00:07
        bootMode: "legacy"
        rootDeviceHints:
          deviceName: "/dev/vda"
pullSecret: 'PULLSECRET'
sshKey: 'SSHPUBKEY'
